# Generated by Django 4.0.4 on 2023-06-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilledOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ontology name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owl', models.FileField(blank=True, default=None, null=True, upload_to='owl/')),
                ('text', models.FileField(blank=True, default=None, null=True, upload_to='texts/')),
                ('facts', models.FileField(blank=True, default=None, null=True, upload_to='facts/')),
                ('result', models.FileField(blank=True, default=None, null=True, upload_to='owl_filled/')),
                ('status', models.CharField(default='pending', max_length=128, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ontology name')),
                ('owl', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
